export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const LOAD_CREDIT_REQUEST = "LOAD_CREDIT_REQUEST";
export const LOAD_CREDIT_SUCCESS = "LOAD_CREDIT_SUCCESS"
export const LOAD_CREDIT_FAIL = "LOAD_CREDIT_FAIL"

export const GENERATE_IMAGE_REQUEST = "GENERATE_IMAGE_REQUEST";
export const GENERATE_IMAGE_SUCCESS = "GENERATE_IMAGE_SUCCESS"
export const GENERATE_IMAGE_FAIL = "GENERATE_IMAGE_FAIL"

export const RAZOR_PAYMENT_REQUEST = "RAZOR_PAYMENT_REQUEST";
export const RAZOR_PAYMENT_SUCCESS = "RAZOR_PAYMENT_SUCCESS"
export const RAZOR_PAYMENT_FAIL = "RAZOR_PAYMENT_FAIL"

export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS"
export const VERIFY_PAYMENT_FAIL = "VERIFY_PAYMENT_FAIL"